# SELECT USER_ID, PRODUCT_ID
# FROM ONLINE_SALE
# GROUP BY USER_ID, PRODUCT_ID
# HAVING COUNT(*) >= 2
# ORDER BY USER_ID, PRODUCT_ID DESC;

SELECT DISTINCT O1.USER_ID, O1.PRODUCT_ID
FROM ONLINE_SALE AS O1
JOIN ONLINE_SALE AS O2
ON O1.USER_ID = O2.USER_ID
AND O1.PRODUCT_ID = O2.PRODUCT_ID
AND O1.ONLINE_SALE_ID <> O2.ONLINE_SALE_ID
ORDER BY USER_ID, PRODUCT_ID DESC;